name: GitHub Snake Game

on:
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # Allow manual triggering of the workflow
  workflow_dispatch:
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake animations
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/blue-wave.gif?color_snake=#00a8ff&color_dots=#004080,#0066cc,#0099ff,#33ccff,#80dfff&background=transparent
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&background=transparent
            dist/forest.gif?color_snake=#228B22&color_dots=#98FB98,#556B2F,#2E8B57,#6B8E23,#3CB371&background=transparent
            dist/fire.gif?color_snake=red&color_dots=#FF6347,#FF4500,#FF8C00,#FFD700,#DC143C&background=transparent
            dist/galaxy.gif?color_snake=purple&color_dots=#9400D3,#8A2BE2,#4B0082,#6A5ACD,#483D8B&background=transparent
            dist/candy.gif?color_snake=pink&color_dots=#FF69B4,#FFC0CB,#FFD700,#FFA07A,#FF4500&background=transparent
            dist/sunset.gif?color_snake=#FF4500&color_dots=#FFD700,#FF6347,#FF7F50,#FF4500,#FF8C00&background=transparent
            dist/ice.gif?color_snake=blue&color_dots=#00FFFF,#AFEEEE,#5F9EA0,#4682B4,#B0E0E6&background=transparent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Validate the generated files
      - name: Validate Outputs
        run: |
          ls -l dist/
          file dist/*

      # Step 4: Deploy the generated files to the 'output' branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation [skip ci]"
